name: diyar-cypress-todo-project

on:
  push:
    branches: ["main"]

    jobs:
      test:
        runs-on: macos-latest
        steps:
          -uses: actions/checkout@v4
          -uses: cypress-io/github-action@v4