name: Diyar run cypress todo application

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
          with:
            record: true
          env:
          CYPRESS_RECORD_KEY:c83ae964-c5ef-45db-a866-d6577e4edc68
